### ISSUE TITLE
Extract XMPP-related API to an interface

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/CyclopsChat#19]
As a first step towards #9, let's extract the required XMPP-related API to a `Cyclops.Xmpp` assembly (`IXmppClient` and friends).

**Comment by vitalyster** [comment]
As XMPP is dead, maybe better to not being protocol dependent and extract protocol related things to IChatClient interface, so different protocol can be used in the future?

**Comment by ForNeVeR** [comment]
> As XMPP is dead

Hardly an argument. Many of us share this status, so what now exactly?

> maybe better to not being protocol dependent and extract protocol related things to IChatClient interface, so different protocol can be used in the future?

For now, I'm not setting such a goal for this project. If any, [Smith](https://github.com/ForNeVeR/Smith) is my personal ongoing attempt at lifting a client to a multi-protocol level.

Though, the PRs/forks are always open. Or a discussion, if you're _that_ interested in making a multi-protocol client out of Cyclops. In such case, this may be a first step towards the client generalization: first, remove all the protocol-specific references spattered all over the place, and concentrate them in one assembly (which will help to refactor everything in a desired way, then).
